# On macOS we need to add some flags to rustc to prevent the following error:
# 
# Traceback (most recent call last):
#   File "/Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/site-packages/xain_aggregators/weighted_average.py", line 2, in <module>
#     import pickle
#   File "/Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/pickle.py", line 33, in <module>
#     from struct import pack, unpack
#   File "/Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/struct.py", line 13, in <module>
#     from _struct import *
# ImportError: dlopen(/Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so, 2): Symbol not found: __PyFloat_Pack2
#   Referenced from: /Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
#   Expected in: flat namespace
#  in /Users/user_xyz/.pyenv/versions/3.7.4/lib/python3.7/lib-dynload/_struct.cpython-37m-darwin.so
# 
# https://github.com/PyO3/pyo3#using-rust-from-python
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
