stages:
  - qa

image: python:3.6

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - ./scripts/setup.sh

lint:
  stage: qa
  script:
  - ./scripts/lint.sh
  allow_failure: true

test:
  stage: qa
  script:
  - ./scripts/test.sh
