stages:
  - qa

image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - ./scripts/setup.sh

test:
  stage: qa
  script:
    - ./scripts/test.sh

test_slow:
  stage: qa
  script:
    - ./scripts/test_slow.sh
