version: "3.7"
services:

  influxdb:
    image: influxdb:1.7 # current stable version, v2 is in Beta
    hostname: influxdb
    environment:
      INFLUXDB_DB: metrics
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - xain-fl-rs
    ports:
      - "8086:8086"

  keycloak:
    image: jboss/keycloak:8.0.2
    hostname: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: adminadmin
      DB_VENDOR: h2
    networks:
      - xain-fl-rs
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana
    depends_on:
      - keycloak
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - xain-fl-rs
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "OAuth"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "c3fbd14d-dfe9-4dc3-9894-8a97bc6c6575"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://localhost:8080/auth/realms/master/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://keycloak:8080/auth/realms/master/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://keycloak:8080/auth/realms/master/protocol/openid-connect/userinfo"
      GF_SERVER_ENFORCE_DOMAIN: "false"

  coordinator-rs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - influxdb
    networks:
      - xain-fl-rs
    ports:
      - "5555:5555"

  aggregator-rs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - influxdb
    networks:
      - xain-fl-rs
    ports:
      - "6666:6666"

volumes:
  influxdb-data:

networks:
  xain-fl-rs:
