[package]
name = "xain-coordinator"
version = "0.1.0"
authors = ["The XAIN developers"]
edition = "2018"

exclude = [ "/test-data" ]

[dependencies]
log = "0.4.8"
async-std = "0.99"
clap = "2.33.0"

ndarray = "0.12.1"
ndarray-npy = { version = "0.4", default-features = false }
