[package]
name = "xain-grpc"
version = "0.1.0"
authors = ["The XAIN developers"]
edition = "2018"

[dependencies]
clap = "2"
futures = "0.1"
grpcio = "0.5.0-alpha.4"
log = "0.4"
protobuf = "2.8.1"
slog = "2"
slog-async = "2"
slog-scope = "2"
slog-stdlog = "2"
slog-term = "2"
