version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    resource_class: xlarge

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./scripts/test.sh

      - run:
          name: run tests slow
          command: |
            . venv/bin/activate
            ./scripts/test_slow.sh

      - run:
          name: run tests benchmark
          command: |
            . venv/bin/activate
            train --benchmark_name=integration_test
