version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./scripts/test.sh
  tests_slow:
    docker:
      - image: circleci/python:3.7
    resource_class: xlarge
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests slow
          command: |
            . venv/bin/activate
            ./scripts/test_slow.sh

  tests_benchmark:
    docker:
      - image: circleci/python:3.7
    resource_class: large
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests benchmark
          command: |
            . venv/bin/activate
            train --benchmark_name=integration_test

workflows:
  version: 2.1
  qa:
    jobs:
      - tests
      - tests_slow
      - tests_benchmark
