# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: setup the python project
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

  tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./scripts/test.sh

  tests_slow:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests slow
          command: |
            . venv/bin/activate
            ./scripts/test_slow.sh

  tests_benchmark:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests benchmark
          command: |
            . venv/bin/activate
            train --benchmark_name=integration_test

workflows:
  version: 2.1
  qa:
    jobs:
      - build
      - tests:
          requires:
            - build
      - tests_slow:
          requires:
            - build
      - tests_benchmark:
          requires:
            - build
