log_level = "debug"
aggregator_url = "http://localhost:8081"

[api]
bind_address = "0.0.0.0:8081"

[rpc]
bind_address = "0.0.0.0:5555"
aggregator_address = "aggregator:6666"

[federated_learning]
rounds = 10
participants_ratio = 0.5
min_clients = 5
heartbeat_timeout = 15