log_level = "trace"

[aggregation.python]
module = "xain_aggregators.dummy"
class = "Aggregator"

[api]
bind_address = "localhost:8082"

[rpc]
bind_address = "localhost:6666"
coordinator_address = "localhost:5555"
