[logging]
level = "trace"
telemetry = { jaeger_endpoint = "127.0.0.1:6831", service_name = "aggregator" }

[aggregation.python]
module = "xain_aggregators.weighted_average"
class = "Aggregator"

[api]
bind_address = "localhost:8082"

[rpc]
bind_address = "localhost:6666"
coordinator_address = "localhost:5555"
