log_level = "debug"
aggregator_url = "http://localhost:8081"

[api]
bind_address = "localhost:8080"

[rpc]
bind_address = "localhost:5555"
aggregator_address = "localhost:6666"

[federated_learning]
rounds = 10
participants_ratio = 0.5
min_clients = 5
