aggregator_url = "http://10.10.100.9:8082"

[logging]
level = "debug"
telemetry = { jaeger_endpoint = "jaeger:6831", service_name = "coordinator" }

[api]
bind_address = "0.0.0.0:8081"

[rpc]
bind_address = "0.0.0.0:5555"
aggregator_address = "aggregator:6666"

[federated_learning]
rounds = 100
participants_ratio = 0.8
min_clients = 1000
heartbeat_timeout = 15

[metric_store]
database_url = "http://influxdb:8086"
database_name = "metrics"
