[package]
name = "controller"
version = "0.1.0"
authors = ["The XAIN developers"]
edition = "2018"

exclude = [ "/test-data" ]

[dependencies]
async-std = "0.99"
ndarray = "0.12.1"
ndarray-npy = { version = "0.4", default-features = false }
