on: [push]

name: Python-CI

jobs:
  sdk_lint_and_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    env:
        working-directory: ./python/sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-dev-${{ hashFiles('python/sdk/setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -e .[dev]
        working-directory: ${{env.working-directory}}

      - name: black
        run: |
          black --check setup.py xain_sdk
        working-directory: ${{env.working-directory}}

      - name: isort
        run: |
          isort --check-only --diff --settings-path=../.isort.cfg -rc setup.py xain_sdk
        working-directory: ${{env.working-directory}}

      - name: pylint
        run: |
          pylint --rcfile=../.pylintrc xain_sdk
        working-directory: ${{env.working-directory}}

      - name: mypy
        run: |
          mypy --config-file=../mypy.ini xain_sdk
        working-directory: ${{env.working-directory}}
        continue-on-error: true

      - name: PyTest
        run: |
          pytest -v
        working-directory: ${{env.working-directory}}
        continue-on-error: true

  aggregator_lint_and_test:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true
    env:
        working-directory: ./python/aggregators
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-dev-${{ hashFiles('python/aggregators/setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -e .[dev]
        working-directory: ${{env.working-directory}}

      - name: black
        run: |
          black --check setup.py xain_aggregators
        working-directory: ${{env.working-directory}}

      - name: isort
        run: |
          isort --check-only --diff --settings-path=../.isort.cfg -rc setup.py xain_aggregators
        working-directory: ${{env.working-directory}}

      - name: pylint
        run: |
          pylint --rcfile=../.pylintrc xain_aggregators
        working-directory: ${{env.working-directory}}

      - name: mypy
        run: |
          mypy --config-file=../mypy.ini xain_aggregators
        working-directory: ${{env.working-directory}}
        continue-on-error: true

      - name: PyTest
        run: |
          pytest -v
        working-directory: ${{env.working-directory}}
        continue-on-error: true
