on: [push]

name: Rust-CI

jobs:
  check:
    name: rust-build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@master

      - name: install nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly

      - name: cargo check
        working-directory: ./rust
        run: cargo check

  test:
    name: rust-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@master

      - name: install nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: rustfmt, clippy

      - name: cargo test
        working-directory: ./rust
        run: cargo test

  clippy:
    name: rust-clippy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@master
      - name: install nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: clippy

      - name: cargo clippy
        working-directory: ./rust
        # For now, allow this to fail
        run: cargo clippy -- -D warnings || true

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@master

      - name: install nightly
        uses: actions-rs/toolchain@v1
        with:
            profile: minimal
            toolchain: nightly
            components: rustfmt

      - name: cargo fmt
        working-directory: ./rust
        run: cargo fmt --all -- --check
